apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: eso-test-01
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        key: psql-test-postgresql
      secretKey: postgres-password
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: my-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: psql-test-postgresql

