apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret-2
  namespace: eso-test-01
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        key: dockercreds
      secretKey: .dockerconfigjson
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: my-secret-store
  target:
    template:
      type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
    deletionPolicy: Retain
    name: dockercreds
