apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: my-secret-store
  namespace: eso-test-01
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: aws-secret
          secretAccessKeySecretRef:
            key: secret
            name: aws-secret
      region: us-east-2
      service: SecretsManager

